version: '3.8'
services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    ports:
      - "9042:9042" # Puerto por defecto de Cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_SEEDS: "cassandra"
    networks:
      - my-network

  app:
    build:
      context: . # Asegúrate de que tu Dockerfile esté en la raíz del proyecto
    container_name: node-app
    depends_on:
      - cassandra
    environment:
      - NODE_ENV=development
      - CASSANDRA_CONTACT_POINT=cassandra # Utiliza el nombre del servicio de Cassandra
    networks:
      - my-network
    ports:
      - "3000:3000" # Mapea el puerto de tu aplicación

networks:
  my-network:
    driver: bridge
